version: '3'
services:
  db:
    build:
      context: ./database
    image: postgres:latest
    restart: always
    container_name: practice-01-postgres
    ports:
      - 5432:5432  # Adjust the port mapping if necessary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresmaster
      POSTGRES_DB: postgres
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend  # Specify the path to the backend directory
    restart: always
    ports:
      - 8000:8000  # Adjust the port mapping if necessary
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend  # Specify the path to the frontend directory
    restart: always
    ports:
      - 8080:8080  # Adjust the port mapping if necessary
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

networks:
  mynetwork:
